### ISSUE TITLE
QUESTION - How to use this library to calculate the distance between a token and wall ?

### ISSUE THREAD

**Issue by p4535992** [dwonderley/lib-find-the-path#4]
Hello sorry for the inconvenience I'm trying to improve my [arms-reach](https://github.com/p4535992/foundryvtt-arms-reach) project and I found your library, I have a bit of difficulty in understanding how to use it.

If I have not misunderstood the possibilities of this library.

Could you provide an example of how to retrieve the distance between a token and a wall?

An example of the neighbor search you implemented to retrieve the closest token to the selected wall?

**Comment by dwonderley** [comment]
Sorry, I took a break from this project to work on some others / wait for FVTT to stabilize after the 0.8.x series of updates. I'm planning to get back into it soon. Anyway, this is probably way too late, but to answer your questions...
I'm not too familiar with the wall api, so I will assume you have some x, y pixel coordinates to work with. You can compute the distance from the token to a wall (with path planning) using the following:
```
const token = canvas.tokens.get (id);
// You can also use the Euclidean or Chebyshev (i.e. dnd 5e's) distance metrics
const pf = game.FindThePath.Manhattan.PointFactory;
// You can set this to anything >= 0
const movementRange = Infinity;
wallCoords = getWallCoords (wall);
const path = await PathManager.pathToPoint (pf.fromToken (token), pf.fromPixel (wallCoords), movementRange);
```
That's using the path finding, of course. If you don't need path finding (i.e. you just want a straight-line distance), you can use the Point class' Chebyshev, Manhattan, or Euclidean static methods.
```
p1 = pf.fromToken(token)l;
p2 = pf.fromPixel(wallCoords);
dist = Point.Manhattan(p1, p2);
```
You don't need this library for that though. I think Foundry exposes methods for that already.

I have a couple of disclaimers, though.
First, this wasn't made to path find to walls; it was made to avoid them. I think it should still work if you turn off collision checking. If not, it might end up failing to find a path because it collides with the wall it's trying to find. In that case, you could find a path to the nearest neighbor of the wall (make a Point at the pixel coordinates of the wall, get the Point's neighbors using Point.neighbors, find the neighbor that is closest to the token, then plan a path to that Point). You'd probably also have to check that the neighbor isn't also a wall.
Second, walls can stretch across multiple tiles. Path planning to a wall could mean a variety of things. I suggest pathing to the point on the wall closest to the token. You could do that by finding the vector from the token to the wall (iirc, this is provided by Foundry) and adding it to the token's position. 
Third, if you use Segments, token size will be automatically handled. I believe if you give the path finder a token, it will use Segments without any input from you.
If you have other questions, I'd be happy to answer. There is also some example code in the wiki.

**Comment by p4535992** [comment]
Ty very much, i will give a try when i rewrite everything for 0.8.X.
